project/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('todo.urls',namespace='todo')),
    path('',include('users.urls',namespace='users')),
      
    path('accounts/', include('django.contrib.auth.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todo/urls.py
from . import views
from django.urls import path


app_name = 'todo' 
urlpatterns =[
    # path('',views.TaskListView.as_view(),name='tasklist'),
    path('',views.tasks,name='tasks'),
    path('<int:task_id>/', views.change_status, name='change_status'),
    path('delete/<int:task_id>/', views.task_delete, name='task_delete'),
    path('delete_not_done/', views.tasks_not_done_delete,name='tasks_not_done_delete'),
    path('delete_done/', views.tasks_done_delete,name='tasks_done_delete'),
    
    path('edit/<int:task_id>/', views.task_edit, name='task_edit'),
]

users/urls.py
from django.urls import path
from . import views 


app_name = 'users'
urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='UserLogin'),
    path('logout/', views.UserLogoutView.as_view(),name='UserLogout'),
    path('signup/', views.UserFormView.as_view(), name='UserForm'),
    path('profileupdate/', views.profile_user_edit, name='profile_user_edit'),
    path('profile/', views.profile_view, name='profile_view'),
]

todo/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Task(models.Model):
    T_name = models.CharField(max_length=15)

    T_status = models.BooleanField(default=False)

    T_published = models.DateTimeField(auto_now_add=True,auto_now=False)

    T_user = models.ForeignKey(User, on_delete=models.CASCADE,related_name='U_tasks')

    def __str__(self):
        return self.T_name

    class Meta:
        ordering = ('-T_published',)

todo/forms.py
from django import forms
from .models import Task
from django.core.exceptions import ValidationError

class AddTask(forms.ModelForm):
    T_name = forms.CharField(max_length=15,label='add task')
    
    class Meta:
        model= Task
        fields = ('T_name',)


    



class EditTask(forms.ModelForm):
    T_name = forms.CharField(max_length=15)
    
    class Meta:
        model= Task
        fields = ('T_name',)

todo/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.views.generic import ListView
from .models import Task
from django.utils import timezone
from .forms import AddTask,EditTask
from django.contrib import messages
from django.contrib.auth.decorators import login_required




@login_required(login_url='users:UserLogin')
def tasks(request):
    tasks = Task.objects.filter(T_user=request.user)
    
    if request.method == 'POST':
        form = AddTask(request.POST)
        if 'T_name' in request.POST:
            T_name = request.POST['T_name']
            if T_name:
                if form.is_valid():
                        T_name = form.cleaned_data['T_name']  
                        if T_name:
                            newtask= form.save(commit=False)
                            newtask.T_status = False
                            newtask.T_user = request.user
                            newtask= form.save()
                
                else: 
                        print('novalid')
                        # Get the text that was entered in `T_name`
                        T_name = request.POST.get("T_name")
                        length_of_T_name = len(T_name)
                        print(length_of_T_name)
                        # Simply send your own message
                        messages.warning(request, f"Error: maximum length limit is 15 characters (it has {length_of_T_name}).")
                
                return redirect('todo:tasks')
                  
            else:
                messages.warning(request, 'please add task.')
                return redirect('todo:tasks')
    else:
        form = AddTask()    
  
    context = {
        'tasks': tasks,
        'tasks_done': tasks.filter(T_status=True),
        'tasks_not_done': tasks.filter(T_status=False),
        'form' : form ,
        'title': 'To DO Tasks',
        'sub_title': 'index',
    }
    return render(request, 'todo/index.html', context)
# ----------------------------------------------------




# ---change status -- done/not done ---#
def change_status(request, task_id):
    tasks = Task.objects.all()
    task = get_object_or_404(Task,id=task_id)
    if task.T_status == False:
        task.T_status = True
        task.save()
    
    elif task.T_status == True :
        task.T_status = False
        task.save()

    return redirect('todo:tasks')
# ----------------------------------------- 




# --- task delete ---------------------------
@login_required(login_url='users:UserLogin')
def task_delete(request, task_id):
    task = get_object_or_404(Task,id=task_id)
    task.delete()
    return redirect('todo:tasks')
# ---------------------------




#  all tasks_not_done_delete ----
@login_required(login_url='users:UserLogin')
def tasks_not_done_delete(request):
    tasks = Task.objects.filter(T_status=False)
    tasks.delete()
    return redirect('todo:tasks')
# ---------------------------



#  all tasks_done_delete ----
@login_required(login_url='users:UserLogin')
def tasks_done_delete(request):
    tasks = Task.objects.filter(T_status=True)
    tasks.delete()
    return redirect('todo:tasks')
# ---------------------------





# ----task_edit ---- need complate !------------------
@login_required(login_url='users:UserLogin')
def task_edit(request,task_id):
    if request.method == 'POST':
       
        T_name = request.POST.get('T_name_edit')
        if T_name:
            length_of_T_name = len(T_name)
            print(length_of_T_name)
            if length_of_T_name > 15:
                # Simply send your own message
                messages.warning(request, f"Error: maximum length limit is 15 characters (it has {length_of_T_name}).")
                return redirect('todo:tasks')
            
            else:
                task_id = request.POST.get('edit_id')
                T_name = request.POST.get('T_name_edit')
                T_user = request.user
                T_published = timezone.now()
                task = Task(id=task_id, T_name=T_name,T_user=T_user, T_published=T_published)
                task.save()
                messages.success(request, 'edit successfully.')
                return redirect('todo:tasks')
   
    else:
        return redirect('todo:tasks')
# ----------------------------------------------

todo/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <!doctype html>
<html lang="en">
  {% load static %}
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    
    {% comment %} fontawesome {% endcomment %}
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <link rel="stylesheet" href="{% static 'css/todo/my_style.css' %}">


    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'image/favicon.ico' %}">
    
    <title>    
        {{ title }} | {{ sub_title }}
    </title>
  </head>

{% comment %} ----body start ---- {% endcomment %}
  
  
  
<body class='pat'>
{% comment %} nabar start {% endcomment %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <!-- logo start -->
        <div class="navbar-brand rotate-n-15  mr-3">
            <i class="fas fa-tasks fa-3x"></i>
        </div>
        <div class="navbar-brand mb-0 h1"><h1> To Do <sup>!</sup></h1></div>
        <!-- logo end -->
        
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
         <a class="nav-link pt-2" href="{% url 'todo:tasks' %}"><i class="far fa fa-home mt-2 "></i> Home</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle pt-2" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-user"></i>   Accounts
        </a>
        {% if request.user.is_authenticated %}
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'users:UserLogout' %}">Logout</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'users:profile_view' %}">Profile</a>
        </div>
        {% else %}
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'users:UserLogin' %}">Login</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'users:UserForm' %}">Register</a>
        </div>
        {% endif %}
      </li>
    </ul>
    {% if request.user.is_authenticated %}
        <div class='nav-item'>
            <a href = "{% url 'users:profile_user_edit' %}">   
                {% if user.U_profile.P_image %}
                    <img class="img-fluid rounded-circle border m-2" 
                        style="width: 30px; height:30px;"
                          src="{{user.U_profile.P_image.url}}" 
                          alt="{{user.username}}">
                    <span class='badge badge-light'>Welcome {{ user.username }}</span> 
                {% else %}
                    <img class="img-fluid rounded-circle border m-2" 
                        style="width: 30px; height:30px;"
                          src="{% static 'image/users/default.jpg' %}" 
                          alt="{{user.username}}">
                    <span class='badge badge-light'>Welcome {{ user.username }}</span>
                {% endif %} 
             </a>         
        </div>
    {% endif %}  
  </div>
</nav>
{% comment %} navbar end  {% endcomment %}
{% block content %}
{% endblock content  %}
<br>
<footer class="bg-light text-center text-lg-start">
  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    <center>   
              Copyright&nbsp;&copy;{% now 'Y' %} &nbsp;All rights reserved 
              <br>by <a class="text-dark" href="https://github.com/mayals"><i class="fab fa-github-alt"></i>&nbsp;mayals</a>, 
            </center>
  </div>
  <!-- Copyright -->
</footer>


  
    <script type="text/javascript" src="{% static 'js/my_javascript.js' %}"></script>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>