project/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('todo.urls',namespace='todo')),
    path('',include('users.urls',namespace='users')),
      
    path('accounts/', include('django.contrib.auth.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todo/urls.py
from . import views
from django.urls import path


app_name = 'todo' 
urlpatterns =[
    # path('',views.TaskListView.as_view(),name='tasklist'),
    path('',views.tasks,name='tasks'),
    path('<int:task_id>/', views.change_status, name='change_status'),
    path('delete/<int:task_id>/', views.task_delete, name='task_delete'),
    path('delete_not_done/', views.tasks_not_done_delete,name='tasks_not_done_delete'),
    path('delete_done/', views.tasks_done_delete,name='tasks_done_delete'),
    
    path('edit/<int:task_id>/', views.task_edit, name='task_edit'),
]

todo/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Task(models.Model):
    T_name = models.CharField(max_length=15)

    T_status = models.BooleanField(default=False)

    T_published = models.DateTimeField(auto_now_add=True,auto_now=False)

    T_user = models.ForeignKey(User, on_delete=models.CASCADE,related_name='U_tasks')

    def __str__(self):
        return self.T_name

    class Meta:
        ordering = ('-T_published',)

todo/forms.py
from django import forms
from .models import Task
from django.core.exceptions import ValidationError

class AddTask(forms.ModelForm):
    T_name = forms.CharField(max_length=15,label='add task')
    
    class Meta:
        model= Task
        fields = ('T_name',)


    



class EditTask(forms.ModelForm):
    T_name = forms.CharField(max_length=15)
    
    class Meta:
        model= Task
        fields = ('T_name',)

todo/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.views.generic import ListView
from .models import Task
from django.utils import timezone
from .forms import AddTask,EditTask
from django.contrib import messages
from django.contrib.auth.decorators import login_required




@login_required(login_url='users:UserLogin')
def tasks(request):
    tasks = Task.objects.filter(T_user=request.user)
    
    if request.method == 'POST':
        form = AddTask(request.POST)
        if 'T_name' in request.POST:
            T_name = request.POST['T_name']
            if T_name:
                if form.is_valid():
                        T_name = form.cleaned_data['T_name']  
                        if T_name:
                            newtask= form.save(commit=False)
                            newtask.T_status = False
                            newtask.T_user = request.user
                            newtask= form.save()
                
                else: 
                        print('novalid')
                        # Get the text that was entered in `T_name`
                        T_name = request.POST.get("T_name")
                        length_of_T_name = len(T_name)
                        print(length_of_T_name)
                        # Simply send your own message
                        messages.warning(request, f"Error: maximum length limit is 15 characters (it has {length_of_T_name}).")
                
                return redirect('todo:tasks')
                  
            else:
                messages.warning(request, 'please add task.')
                return redirect('todo:tasks')
    else:
        form = AddTask()    
  
    context = {
        'tasks': tasks,
        'tasks_done': tasks.filter(T_status=True),
        'tasks_not_done': tasks.filter(T_status=False),
        'form' : form ,
        'title': 'To DO Tasks',
        'sub_title': 'index',
    }
    return render(request, 'todo/index.html', context)
# ----------------------------------------------------




# ---change status -- done/not done ---#
def change_status(request, task_id):
    tasks = Task.objects.all()
    task = get_object_or_404(Task,id=task_id)
    if task.T_status == False:
        task.T_status = True
        task.save()
    
    elif task.T_status == True :
        task.T_status = False
        task.save()

    return redirect('todo:tasks')
# ----------------------------------------- 




# --- task delete ---------------------------
@login_required(login_url='users:UserLogin')
def task_delete(request, task_id):
    task = get_object_or_404(Task,id=task_id)
    task.delete()
    return redirect('todo:tasks')
# ---------------------------




#  all tasks_not_done_delete ----
@login_required(login_url='users:UserLogin')
def tasks_not_done_delete(request):
    tasks = Task.objects.filter(T_status=False)
    tasks.delete()
    return redirect('todo:tasks')
# ---------------------------



#  all tasks_done_delete ----
@login_required(login_url='users:UserLogin')
def tasks_done_delete(request):
    tasks = Task.objects.filter(T_status=True)
    tasks.delete()
    return redirect('todo:tasks')
# ---------------------------





# ----task_edit ---- need complate !------------------
@login_required(login_url='users:UserLogin')
def task_edit(request,task_id):
    if request.method == 'POST':
       
        T_name = request.POST.get('T_name_edit')
        if T_name:
            length_of_T_name = len(T_name)
            print(length_of_T_name)
            if length_of_T_name > 15:
                # Simply send your own message
                messages.warning(request, f"Error: maximum length limit is 15 characters (it has {length_of_T_name}).")
                return redirect('todo:tasks')
            
            else:
                task_id = request.POST.get('edit_id')
                T_name = request.POST.get('T_name_edit')
                T_user = request.user
                T_published = timezone.now()
                task = Task(id=task_id, T_name=T_name,T_user=T_user, T_published=T_published)
                task.save()
                messages.success(request, 'edit successfully.')
                return redirect('todo:tasks')
   
    else:
        return redirect('todo:tasks')
# ----------------------------------------------

todo/templates/todo/index.html
{% extends 'base.html'  %}
{% load crispy_forms_tags %}


{% block content %}

<br><br>

<div class='container'>

<!-- if messages  -->
                          {% if messages %}
                              {% for message in messages %}
                                  <div class="alert alert-{{message.tags}}">
                                      {{message}}
                                  </div>
                              {% endfor %} 
                          {% endif %}
<!-- end if messages  -->



    <div class="card bg-secondary text-dark mb-3">
      <div class="card-header"><h2 class="text-light text-center">To DO Tasks</h2></div>   
        <div class="card-body bg-light table-responsive">
              <!-- button Delete All --> 
              <a class="btn btn-danger btn-sm float-left mb-2" href="{% url 'todo:tasks_not_done_delete' %}" role="button"><i class="text-light far fa-trash-alt fa-1x"></i>
                 Delete All
              </a>   
              
              <table class="table table-hover table-sm">
              <tbody>
          
                {% for task in tasks_not_done %}
                <!--start  tasks not done list --> 
                <tr>     
                    {% if task.T_status == False %}
                        <!-- tasks not done name --> 
                        <td>
                          <h5 class='font-weight-bold'>
                            <a href="{% url 'todo:change_status' task_id=task.id %}" class="btn" role="button" aria-pressed="true">
                              <i class="text-secondary far fa-clock fa-2x"></i>
                            </a>
                            <span>{{ task.T_name }}</span>
                          </h5>
                        <td/>

                        <!-- tasks not done date -->
                        <td>
                            <small><span class='text-muted font-italic text-lef'>{{ task.T_published|date:'d-m-Y' }}</span><small>
                        </td>








                      <!--############  start button edit tasks not done and modal for it ##############-->
                        <!-- button edit tasks not done -->
                        <!-- this buton only open jave script alert id="exampleModal"-->
                        <td>
                          <a  data-target="#exampleModal" href="{% url 'todo:task_edit' task_id=task.id %}" type='submit' data-toggle="modal"  class='float-right btn'>
                              <i class="text-info far fa-edit fa-1x"></i>
                          </a>
                        </td>

                          <!-- start  modal of button edit tasks not done -->
                          <div id="exampleModal" class="modal fade"  tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                  <div class="modal-dialog modal-dialog-centered" role="document">
                                    <div class="modal-content">
                                      <!-- start  modal-header -->
                                      <div class="modal-header">
                                          <h5 class="modal-title" id="exampleModalLabel">Edit Task</h5>
                                          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                          <span aria-hidden="true">&times;</span>
                                          </button>
                                      </div>
                                      <!-- start  modal-body   form -->
                                      <div class="modal-body">
                                            <form method='Post' action="{% url 'todo:task_edit' task_id=task.id %}">
                                            <div class="form-group">  
                                               {% csrf_token %}
                                                <div class="form-group">
                                                    <input name='T_name_edit' id='T_name_edit' value="{{task.T_name}}" class="form-control form-control-lg" type="text">
                                                    <input name='edit_id'  id='edit_id' value="{{task.id}}" class="form-control form-control-lg" type="hidden">
                                                </div> 
                                                <!-- start  modal-foter inside modal body -->
                                                <div class="modal-footer" > 
                                                    <button  type='submit' class="btn btn-success float-right" id="edit_task_btn" title="Edit Task">
                                                        <i class="text-light far fa-edit fa-1x"></i> 
                                                          Task
                                                    </button>
                                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">
                                                          Close
                                                    </button>
                                                </div>
                                              </div>
                                              </form>
                                      </div>
                                      <!-- end modal-body form -->
                                    </div>
                                  </div>
                          </div>
                          <!-- end  modal of button edit tasks not done -->
                      <!--############ end button edit tasks not done and modal for it ##############-->
                          
















                        <!--button delete not done task  -->
                        <td>
                          <a href="{% url 'todo:task_delete' task_id=task.id %}" class='float-right btn'>
                              <i class="text-danger far fa-trash-alt fa-1x"></i>
                          </a>
                        </td>
                </tr>
                <!--end tasks not done list --> 

                    {% else %}
                <!-- tasks done list -->     
                <tr>    
                        <td>
                              <h5 class='font-weight-light text-muted'>
                                <a href="{% url 'todo:change_status' task_id=task.id %}" class="btn" role="button" aria-pressed="true">
                                  <i class="text-success fas fa-check fa-2x"></i>
                                </a> 
                                <span><del> {{ task.T_name }}</del></span>
                              </h5>
                        </td>
                </tr>
                  <!--end tasks done list -->      
                    {% endif %} 
    
                {% endfor %} 
                  
                        
                        <!-- start row add new task form -->
                        <tr class="card-footer bg-light">
                          <form method='POST' class="form-group"> 
                              {% csrf_token %}
                              <div>
                                <input name='T_name' class="form-control form-control-lg" type="text" placeholder="Enter your Task (Max. 15 characters)">
                                <input name='task_id' class="form-control form-control-lg" type="hidden">
                              </div>
                              <div>
                                <button  class="btn btn-warning btn-sm btn-block mb-3 mt-1" id="add_task_btn"
                                title="Add a New Task"><i class="fas fa-plus-circle fa-sm"></i>&nbsp;Task</button>
                              </div>
                          </form>        
                        </tr>
                        <!-- end row add new task form -->

                </tbody>
            </table>
        </div> 
      </div>
   {% comment %} end tabe1 {% endcomment %}
    
<br><br>

{% comment %} start table 2 {% endcomment %}
    <div class="card bg-success mb-3">
      <div class="card-header"><h2 class="text-light text-center">Done Tasks</h2></div>   
        <div class="card-body bg-light table-responsive">
            <a class="btn btn-danger btn-small float-left mb-2" href="{% url 'todo:tasks_done_delete' %}" role="button"><i class="text-light far fa-trash-alt fa-1x"></i>
                 Delete All
            </a> 
            
            <table class="table table-hover table-sm">
              <tbody>
                  {% comment %}start row  {% endcomment %}
                  {% comment %} start  end row  {% endcomment %}
                {% for task in tasks_done %}
                        <tr>
                            <td>      
                                {% if task.T_status == False %}
                                    <h5 class='font-weight-bold'>
                                      <a href="{% url 'todo:change_status' task_id=task.id %}" class="btn" role="button" aria-pressed="true">
                                        <i class="text-secondary far fa-clock fa-2x"></i>
                                      </a>
                                      <span>{{ task.T_name }}</span>   
                                    </h5>
                                   
                                {% else %}
                                    <h5 class='font-weight-light text-muted'>
                                      <a href="{% url 'todo:change_status' task_id=task.id %}" class="btn" role="button" aria-pressed="true">
                                      <i class="text-success fas fa-check fa-2x"></i>
                                      </a> 
                                      <span><del> {{ task.T_name }}</del></span>
                                    </h5>
                                {% endif %} 
                            </td>   
                        </tr>     
                {% endfor %} 
                  {% comment %} end tasks not done tble{% endcomment %}
                  {% comment %}start end row  {% endcomment %}        
                </tbody>
              </table>

        </div> 
      </div>
  

     {{ now }}
    </div>


{% endblock content  %}

todo/templates/todo/indexcopy.html
{% extends 'base.html'  %}
{% load crispy_forms_tags %}


{% block content %}

<br><br>

<div class='container'>

<!-- if messages  -->
                          {% if messages %}
                              {% for message in messages %}
                                  <div class="alert alert-{{message.tags}}">
                                      {{message}}
                                  </div>
                              {% endfor %} 
                          {% endif %}
<!-- end if messages  -->



    <div class="card bg-secondary text-dark mb-3">
      <div class="card-header"><h2 class="text-light text-center">To DO Tasks</h2></div>   
        <div class="card-body bg-light table-responsive">
              <!-- button Delete All --> 
              <a class="btn btn-danger btn-small float-left mb-2" href="{% url 'todo:tasks_not_done_delete' %}" role="button"><i class="text-light far fa-trash-alt fa-1x"></i>
                 Delete All
              </a>   
              
              <table class="table table-hover table-sm">
              <tbody>
          
                {% for task in tasks_not_done %}
                <!--start  tasks not done list --> 
                <tr>     
                    {% if task.T_status == False %}
                        <!-- tasks not done name --> 
                        <td>
                          <h5 class='font-weight-bold'>
                            <a href="{% url 'todo:change_status' task_id=task.id %}" class="btn" role="button" aria-pressed="true">
                              <i class="text-secondary far fa-clock fa-2x"></i>
                            </a>
                            <span>{{ task.T_name }}</span>
                          </h5>
                        <td/>

                        <!-- tasks not done date -->
                        <td>
                            <small><span class='text-muted font-italic text-lef'>{{ task.T_published|date:'d-m-Y' }}</span><small>
                        </td>








                      <!--############  start button edit tasks not done and modal for it ##############-->
                        <!-- button edit tasks not done -->
                        <!-- this buton only open jave script alert id="exampleModal"-->
                        <td>
                          <a href="{% url 'todo:task_edit' task_id=task.id %}"  data-target="#exampleModal"  type='submit' data-toggle="modal"  class='float-right btn'>
                              <i class="text-info far fa-edit fa-1x"></i>
                          </a>
                        </td>

                          <!-- start  modal of button edit tasks not done -->
                          <div id="exampleModal" class="modal fade"  tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                  <div class="modal-dialog modal-dialog-centered" role="document">
                                    <div class="modal-content">
                                      <!-- start  modal-header -->
                                      <div class="modal-header">
                                          <h5 class="modal-title" id="exampleModalLabel">Edit Task</h5>
                                          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                          <span aria-hidden="true">&times;</span>
                                          </button>
                                      </div>
                                      <!-- start  modal-body   form -->
                                      <div class="modal-body">
                                            <form method='Post' action="">
                                            <div class="form-group">  
                                                {% csrf_token %}
                                                {{editform}}
                                                <div class="modal-footer" > 
                                                  <button  type='submit' class="btn btn-success float-right" id="edit_task_btn" title="Edit Task">
                                                      <i class="text-light far fa-edit fa-1x"></i>Task   
                                                  </button>
                                                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close
                                                  </button>
                                                </div>    
                                            </div>
                                            </form>
                                      </div>
                                      <!-- end modal-body form -->
                                    </div>
                                  </div>
                          </div>
                          <!-- end  modal of button edit tasks not done -->
                      <!--############ end button edit tasks not done and modal for it ##############-->
                          
















                        <!--button delete not done task  -->
                        <td>
                          <a href="{% url 'todo:task_delete' task_id=task.id %}" class='float-right btn'>
                              <i class="text-danger far fa-trash-alt fa-1x"></i>
                          </a>
                        </td>
                </tr>
                <!--end tasks not done list --> 

                    {% else %}
                <!-- tasks done list -->     
                <tr>    
                        <td>
                              <h5 class='font-weight-light text-muted'>
                                <a href="{% url 'todo:change_status' task_id=task.id %}" class="btn" role="button" aria-pressed="true">
                                  <i class="text-success fas fa-check fa-2x"></i>
                                </a> 
                                <span><del> {{ task.T_name }}</del></span>
                              </h5>
                        </td>
                </tr>
                  <!--end tasks done list -->      
                    {% endif %} 
    
                {% endfor %} 
                  
                        
                        <!-- start row add new task form -->
                        <tr class="card-footer bg-light">
                          <form method='POST' class="form-group" > 
                              {% csrf_token %}
                              <td>
                                <input name='T_name'  class="form-control form-control-lg" type="text" placeholder="Enter your Task (Max. 15 characters)">
                                <input name='task_id' class="form-control form-control-lg" type="hidden">
                              </td>
                              <td>
                                <button  class="btn btn-warning float-right" id="add_task_btn"
                                title="Add a New Task"><i class="fas fa-plus-circle fa-2x"></i>Task</button>
                              </td>
                          </form>        
                        </tr>
                        <!-- end row add new task form -->

                </tbody>
            </table>
        </div> 
      </div>
   {% comment %} end tabe1 {% endcomment %}
    
<br><br><br><br>

{% comment %} start table 2 {% endcomment %}
    <div class="card bg-success mb-3">
      <div class="card-header"><h2 class="text-light text-center">Done Tasks</h2></div>   
        <div class="card-body bg-light table-responsive">
           <a class="btn btn-danger btn-small float-left mb-2" href="{% url 'todo:tasks_done_delete' %}" role="button"><i class="text-light far fa-trash-alt fa-1x"></i>
                 Delete All
              </a> 
            
            <table class="table table-hover table-sm">
              <tbody>
               {% comment %}start row  {% endcomment %}
                   
              {% comment %} start  end row  {% endcomment %}
                {% for task in tasks_done %}
                        <tr>
                            <td>      
                                {% if task.T_status == False %}
                                    <h5 class='font-weight-bold'>
                                      <a href="{% url 'todo:change_status' task_id=task.id %}" class="btn" role="button" aria-pressed="true">
                                      <i class="text-secondary far fa-clock fa-2x"></i>
                                      </a>
                                      <span>{{ task.T_name }}</span>
                                          
                                    </h5>
                                   
                                {% else %}
                                    <h5 class='font-weight-light text-muted'>
                                      <a href="{% url 'todo:change_status' task_id=task.id %}" class="btn" role="button" aria-pressed="true">
                                      <i class="text-success fas fa-check fa-2x"></i>
                                      </a> 
                                      <span><del> {{ task.T_name }}</del></span>
                                    </h5>
                                {% endif %} 
                            </td>   
                        </tr>     
                {% endfor %} 
                 {% comment %} end tasks not done tble{% endcomment %}
                        {% comment %}start end row  {% endcomment %}
                        
                </tbody>
            </table>
        </div> 
      </div>
  

     {{ now }}
</div>


{% endblock content  %}